### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Potterli20** [Chikage0o0/Linux-NetSpeed#19]
./tcp.sh: line 621: conditional binary operator expected
./tcp.sh: line 621: syntax error near `${kernel_version}'
./tcp.sh: line 621: `   elif [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "4" ]] && [[ echo ${kernel_version} | awk -F'.' '{print $2}' -ge 9 ]] || [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "5" ]]; then'

**Comment by Potterli20** [comment]
elif [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "4" ]] && [[ echo ${kernel_version} | awk -F'.' '{print $2}' -ge 9 ]] || [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "5" ]]; then

**Comment by Potterli20** [comment]
系统为centos7.1810

**Comment by qzydustin** [comment]
tcp.sh: line 621: conditional binary operator expected
tcp.sh: line 621: syntax error near `${kernel_version}'
tcp.sh: line 621: `     elif [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "4" ]] && [[ echo ${kernel_version} | awk -F'.' '{print $2}' -ge 9 ]] || [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "5" ]]; then'

**Comment by qzydustin** [comment]
系统 debian 9

**Comment by Glanwu** [comment]
我也遇到了同样的问题

**Comment by jamespan2012** [comment]
同样的问题
tcp.sh: line 621: conditional binary operator expected
tcp.sh: line 621: syntax error near `${kernel_version}'
tcp.sh: line 621: `     elif [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "4" ]] && [[ echo ${kernel_version} | awk -F'.' '{print $2}' -ge 9 ]] || [[ echo ${kernel_version} | awk -F'.' '{print $1}' == "5" ]]; then'
