### ISSUE TITLE
搬瓦工的自带 bbr bug???

### ISSUE THREAD

**Issue by Potterli20** [Chikage0o0/Linux-NetSpeed#25]
net.ipv4.neigh.default.base_reachable_time_ms = 600000
net.ipv4.neigh.default.mcast_solicit = 20
net.ipv4.neigh.default.retrans_time_ms = 250
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.eth0.rp_filter = 0
sysctl: cannot stat /proc/sys/net/ipv4/conf/eth1/rp_filter: 没有那个文件或目录
net.ipv4.tcp_fastopen = 3
sysctl: setting key "net.core.default_qdisc": 没有那个文件或目录
net.core.default_qdisc = fq
sysctl: setting key "net.ipv4.tcp_congestion_control": 没有那个文件或目录
net.ipv4.tcp_congestion_control = bbr
sysctl: setting key "net.core.default_qdisc": 没有那个文件或目录
net.core.default_qdisc = fq
sysctl: setting key "net.ipv4.tcp_congestion_control": 没有那个文件或目录
net.ipv4.tcp_congestion_control = bbr

**Comment by lifansama** [comment]
内核是哪个内核？
`uname -r`

**Comment by Potterli20** [comment]
> 内核是哪个内核？
> `uname -r`

 Arch    : x86_64 (64 Bit)
 Kernel  : 5.1.15-1.el7.elrepo.x86_64

**Comment by Potterli20** [comment]
> 内核是哪个内核？
> `uname -r`

我完全改不了内核

**Comment by baoang** [comment]
好象问题出在这句上
`sysctl: cannot stat /proc/sys/net/ipv4/conf/eth1/rp_filter`
通过
`ip address`查询后，正常是这个目录
`sysctl: cannot stat /proc/sys/net/ipv4/conf/eth0/rp_filter`

它的`/etc/sysctl.conf`文件中有这样三句
```
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.eth0.rp_filter=0
net.ipv4.conf.eth1.rp_filter=0
```
似乎最后一句没必要，大概就是这句产生了上述问题。

**Comment by Potterli20** [comment]
> 好象问题出在这句上
> `sysctl: cannot stat /proc/sys/net/ipv4/conf/eth1/rp_filter`
> 通过
> `ip address`查询后，正常是这个目录
> `sysctl: cannot stat /proc/sys/net/ipv4/conf/eth0/rp_filter`
> 
> 它的`/etc/sysctl.conf`文件中有这样三句
> 
> ```
> net.ipv4.conf.all.rp_filter=0
> net.ipv4.conf.eth0.rp_filter=0
> net.ipv4.conf.eth1.rp_filter=0
> ```
> 
> 似乎最后一句没必要，大概就是这句产生了上述问题。

so?
我也不知道
