### ISSUE TITLE
net.ipv4.tcp_congestion_control

### ISSUE THREAD

**Issue by ghost** [Chikage0o0/Linux-NetSpeed#56]
sysctl: setting key "net.core.default_qdisc": No such file or directory
net.core.default_qdisc = fq
sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory

**Comment by robinren03** [comment]
> sysctl: setting key "net.core.default_qdisc": No such file or directory net.core.default_qdisc = fq sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory

Hey, how do you fix the problem? I come into exactly the same problem when using docker to enable BBR.
